// SPDX-License-Identifier: MIT
import { t } from './i18n.ts'

export function argumentLabel(arg: string): string {
  const labels: Record<string, string> = {
    range: t('range'),
    number: t('number'),
    digits: t('digits'),
    text: t('text'),
    value: t('value'),
    date: t('date'),
    criterion: t('criterion'),
    result_range: t('result_range'),
    lookup_range: t('lookup_range'),
    if_missing: t('if_missing'),
    table: t('table'),
    column: t('column'),
    row: t('row'),
    approximate: t('approximate'),
    rate: t('rate'),
    cash_flows: t('cash_flows'),
    percentile: t('percentile'),
    quartile: t('quartile'),
    order: t('order'),
    position: t('position'),
    delimiter: t('delimiter'),
    ignore_empty: t('ignore_empty'),
    condition: t('condition'),
    result: t('result'),
    match: t('match'),
    default: t('default'),
    fallback: t('fallback'),
    format: t('format'),
    find_text: t('find_text'),
    start: t('start'),
    count: t('count'),
    new_text: t('new_text'),
    year: t('year'),
    month: t('month'),
    day: t('day'),
    months: t('months'),
    end_date: t('end_date'),
    start_date: t('start_date'),
    periods: t('periods'),
    present_value: t('present_value'),
    future_value: t('future_value'),
    payment_timing: t('payment_timing'),
    payment: t('payment'),
    if_true: t('if_true'),
    if_false: t('if_false'),
    exponent: t('exponent'),
    divisor: t('divisor'),
    old_text: t('old_text'),
    function_code: t('function_code'),
  }
  return arg.replace(/[a-z_]+/g, name => labels[name] ?? name)
}
